### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [qumqum22/Polish-draughts#6]
1. Globalne zmienne są nieładne. Globalne zmienne pochodzące z innego modułu (`punktacja.biale` i `punktacja.czarne`) są odrażające. Proszę przerobić program tak, żeby zniknęły. Powinno się dać z nich zrobić atrybuty jakiejś klasy, która połączy niektóre z Pańskich funkcji (2. rozdział Poradnika).
2. Wstawianie zmiennych do pliku o nazwie `const.py` nie jest specjalnie godne polecenia.
3. Pylint pomoże Panu ogarnąć stosowanie białych znaków (2. rozdział).
4. Gracze nie mogą być oznaczani przez -1 i 1. Proszę z tego zrobić stałe (2. rozdział).
5. Nazwy funkcji w `camelCase` nie są pytoniczne. Powinny być w `snake_case`.
6. Kolor (255, 0, 0). :) Proszę poczytać o kolorach w 3. rozdziale.

**Comment by MarcinCiura** [comment]
Rzuciłem okiem na testy. Merytorycznie są w porządku, natomiast zgodnie z regułami sztuki powinien Pan je zrobić, korzystając z modułu unittest (np. kiedyś w pracy zawodowej nie zaakceptują Panu takich ręcznie wyklepanych testów). Zmiana nie będzie trudna: należy przełożyć test_[1-3] z chessboard.py, opakować Pańskie trzy funkcje testujące w klasę i użyć w nich metod `assertTrue()` i `assertEqual()`. W 3. rozdziale Poradnika jest wzorzec pliku z testami jednostkowymi; poradzi Pan sobie z dostosowaniem go do swojego przypadku.

**Comment by qumqum22** [comment]
Poprawiłem testy zgodnie z Pana zaleceniami, pylint podpowiadał mi, że moje 3 funkcje moge wyciągnąć poza klasę, jednak zostawiam je w ciele klasy. Nie widzę dużej różnicy, jednak jeżeli wyciągnięcie ich poza ciało klasy jest lepszym rozwiązaniem, proszę mnie o tym poinformować, taka wiedza z pewnością mi nie zaszkodzi na przyszłość.   github.com github.com   Dziękuje bardzo i przepraszam za kłopot,  Piotr Gucwa, grupa 03 wtorek 18:00, Informatyka, Semestr IV, Wydział Informatyki i Telekomunikacji. 
            
          
     
      
       
        Dnia 19 czerwca 2020 16:11 Marcin Ciura &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 Rzuciłem okiem na testy. Merytorycznie są w porządku, natomiast zgodnie z regułami sztuki powinien Pan je zrobić, korzystając z modułu unittest (np. kiedyś w pracy zawodowej nie zaakceptują Panu takich ręcznie wyklepanych testów). Zmiana nie będzie trudna: należy przełożyć test_[1-3] z chessboard.py, opakować Pańskie trzy funkcje testujące w klasę i użyć w nich metod  assertTrue()  i  assertEqual() . W 3. rozdziale Poradnika jest wzorzec pliku z testami jednostkowymi; poradzi Pan sobie z dostosowaniem go do swojego przypadku.

**Comment by MarcinCiura** [comment]
Doszło do mnie na oba sposoby. Jest nieźle. Jeszcze tylko kosmetyka:
1. Ja bym wpisał treść funkcji `test_...()` do środka odpowiednich metod.
2. Powtarzające się dwa (po uwzględnieniu punktu 1. — trzy, a coś mi się widzi, że wraz ze `score.points_load()` — cztery) pierwsze wiersze każdego testu wyciągnąć do metody `setUp()`.
3. Metodę `reset_game()` wyrzucić — metoda `setUp()` sama załatwi sprawę.
4. [Tu](https://github.com/qumqum22/Polish-draughts/blob/8462c406a1a9a1f0fd0705ed4c94a7d3b19e51d8/tests.py#L50) chyba nie `if ...: break`, tylko `self.assertEqual(...)`.
5. [Tu](https://github.com/qumqum22/Polish-draughts/blob/8462c406a1a9a1f0fd0705ed4c94a7d3b19e51d8/tests.py#L52) też.
6. [Tu](https://github.com/qumqum22/Polish-draughts/blob/8462c406a1a9a1f0fd0705ed4c94a7d3b19e51d8/tests.py#L75) zaś `self.assertFalse(...)`.
7. Pylint mówi, że niektóre metody mogą być wyjęte, bo Pan w nich nie używa `self.assert...()`, a bez nich metody testujące nie są testami.

**Comment by qumqum22** [comment]
Dziękuje bardzo, czy mam to pozmieniać i napisać Panu o zmianach by uzyskać punkty z projektu czy jest to jedynie informacja i nauka dla mnie ?   Życzę miłego dnia,  Piotr Gucwa Dnia 23 czerwca 2020 00:24 Marcin Ciura &lt;notifications@github.com&gt; napisał(a):   Doszło do mnie na oba sposoby. Jest nieźle. Jeszcze tylko kosmetyka:  Ja bym wpisał treść funkcji  test_...()  do środka odpowiednich metod.  Powtarzające się dwa (po uwzględnieniu punktu 1. — trzy, a coś mi się widzi, że wraz ze  score.points_load()  — cztery) pierwsze wiersze każdego testu wyciągnąć do metody  setUp() .  Metodę  reset_game()  wyrzucić — metoda  setUp()  sama załatwi sprawę.  github.com Tu  chyba nie  if ...: break , tylko  self.assertEqual(...) .  github.com Tu  też.  github.com Tu  zaś  self.assertFalse(...) .  Pylint mówi, że niektóre metody mogą być wyjęte, bo Pan w nich nie używa  self.assert...() , a bez nich metody testujące nie są testami.  —  You are receiving this because you modified the open/close state.  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .

**Comment by MarcinCiura** [comment]
To jest wiadomość dla Pana. Może Pan nie zmieniać, ale wtedy mój wysiłek dydaktyczny pójdzie na marne, bo Pan sobie nie utrwali dobrych nawyków (czytanie < pisanie).
